### ISSUE TITLE
Wrong FK relation information

### ISSUE THREAD

**Issue by akurth** [emarsden/pgmacs#12] opened 2024-12-19 10:36 UTC
Hello,

thanks for your efforts in this project. It looks promising and I’m looking forward to be able to use it regularly.

I found the following issue. Looking at table "identifier" with psql the output is as follows:

```
idapi=> \d identifier
                        Table "public.identifier"
   Column    │           Type           │ Collation │ Nullable │ Default
─────────────┼──────────────────────────┼───────────┼──────────┼─────────
 id          │ text                     │           │ not null │
 brand       │ text                     │           │ not null │
 type        │ text                     │           │ not null │
 user_id     │ text                     │           │ not null │
 created     │ timestamp with time zone │           │          │
 lastchanged │ timestamp with time zone │           │          │
Indexes:
    "pk__identifier" PRIMARY KEY, btree (id, brand, type)
    "constr__identifier__userid_type" UNIQUE CONSTRAINT, btree (user_id, type)
Foreign-key constraints:
    "fk__identifier__brand" FOREIGN KEY (brand) REFERENCES user_brand(id) ON UPDATE CASCADE
    "fk__identifier__type" FOREIGN KEY (type) REFERENCES identifier_type(id) ON UPDATE CASCADE
    "fk__identifier__userid_brand" FOREIGN KEY (user_id, brand) REFERENCES user_(id, brand) ON UPDATE CASCADE ON DELETE CASCADE
```

PGmacs shows the following though:

```
PostgreSQL table identifier, owned by  dop
On-disk-size: 48 kB (indexes 32 kB)
Columns:
├ id: text, NOT NULL, PRIMARY KEY pk__identifier
├ brand: text, NOT NULL, REFERENCES user_(id), PRIMARY KEY pk__identifier
├ type: text, NOT NULL, REFERENCES identifier_type(id), UNIQUE constr__identifier__userid_type, PRIMARY KEY pk__identifier
├ user_id: text, NOT NULL, REFERENCES user_(id), UNIQUE constr__identifier__userid_type
├ created: timestamptz
└ lastchanged: timestamptz
Indexes:
  constr__identifier__userid_type UNIQUE  btree (cols: {user_id,type})
  pk__identifier UNIQUE PRIMARY  btree (cols: {id,brand,type})
Row-level access control: not enabled
```

Most important erroneous difference:
The FK reference brand->user_brand(id) got lost and has been replaced by brand->user_(id). If I click on column brand pgmacs also tries to select a user_ with the brand ID, which results in "not found", of course.

I am using emacs 31 from master and PG 17.2. Please let me know if you need further info.

**Comment by emarsden** [comment] 2024-12-19 13:29
This is strange, and I can't reproduce it with Emacs 31. Does it also occur with Emacs 29? 

If this database doesn't contain sensitive information, are you able to share it with me privately (I see it's isn't very large)? Or perhaps only the full schema structure, for example obtained with "pg_dump --schema-only".

**Comment by akurth** [comment] 2024-12-19 15:48
This is only a small part of the DB. I’ll try to strip down the problem to a minimal example and attach the respective schema then.
I suspect this might be a problem with the "user_" table (which I had to name "user_" to avoid conflicts with the internal postgres "user" table).

**Comment by akurth** [comment] 2024-12-19 18:28
[minimal.txt](https://github.com/user-attachments/files/18201798/minimal.txt)

I can reproduce the problem with this minimal example. Please note the difference in the "brand" FK.

psql shows this:

```
minimal=> \d identifier
            Table "public.identifier"
 Column  │ Type │ Collation │ Nullable │ Default
─────────┼──────┼───────────┼──────────┼─────────
 id      │ text │           │ not null │
 brand   │ text │           │ not null │
 user_id │ text │           │ not null │
Indexes:
    "pk__identifier" PRIMARY KEY, btree (id, brand)
Foreign-key constraints:
    "fk__identifier__brand" FOREIGN KEY (brand) REFERENCES user_brand(id) ON UPDATE CASCADE
    "fk__identifier__userid_brand" FOREIGN KEY (user_id, brand) REFERENCES user_(id, brand) ON UPDATE CASCADE ON DELETE CASCADE
```

while pgmacs shows this:

```
PostgreSQL table identifier, owned by  dop
On-disk-size: 16 kB (indexes 8192 bytes)
Columns:
├ id: text, NOT NULL, PRIMARY KEY pk__identifier
├ brand: text, NOT NULL, REFERENCES user_(id), PRIMARY KEY pk__identifier
└ user_id: text, NOT NULL, REFERENCES user_(id)
Indexes:
  pk__identifier UNIQUE PRIMARY  btree (cols: {id,brand})
```

**Comment by emarsden** [comment] 2024-12-20 07:40
Thanks, I can reproduce this issue. The SQL queries we are using don't work with composite (multi-column) foreign key references, that will require some changes.

**Comment by emarsden** [comment] 2024-12-22 13:14
This is fixed in the latest release, thanks for the report.

**Closed by emarsden** 2024-12-22 13:14 UTC
